### ISSUE TITLE
APP CRASH WHEN TRY TO OPEN NOVEL

### ISSUE THREAD

**Issue by muhammadarif1** [Doomsdayrs/shosetsu#20]
#### EXPECTED BEHAVIOR
this application will open the novel well so that users can read whatever novels they want
#### ACTUAL BEHAVIOR
when the user wants to open a novel to read, before the novel is fully loaded this application will stop working and crash.
#### STEP TO REPRODUCE
- download and install the app
- open the app
- click on tree line on the left side
- click on catalogue
- chose novel full or box novel
- wait for a second and novel list will appear
- then chose any novel you want to read
- note the error
#### BUG RECORDING
https://youtu.be/iVlBxn0cJ_g
#### LOGCAT
```FATAL EXCEPTION: AsyncTask #4
Process: com.github.doomsdayrs.apps.shosetsu, PID: 3491
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NoSuchMethodError: No static method encodeBase64String([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/ext.jar)
	at com.github.doomsdayrs.apps.shosetsu.backend.database.Database.serialize(Database.java:126)
	at com.github.doomsdayrs.apps.shosetsu.backend.database.Database.access$000(Database.java:54)
	at com.github.doomsdayrs.apps.shosetsu.backend.database.Database$DatabaseChapter.addToChapters(Database.java:464)
	at com.github.doomsdayrs.apps.shosetsu.backend.async.NovelLoader.doInBackground(NovelLoader.java:86)
	at com.github.doomsdayrs.apps.shosetsu.backend.async.NovelLoader.doInBackground(NovelLoader.java:42)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more```

**Comment by Doomsdayrs** [comment]
What version of android are you running?

**Comment by Doomsdayrs** [comment]
Never mind the above, I think i have solved the issue . Are you capable of compiling the code yourself?

**Comment by muhammadarif1** [comment]
no bro

**Comment by Doomsdayrs** [comment]
[This ](https://cdn.discordapp.com/attachments/598958918839828490/603274787204104211/shosetsu-v1.1.8.1-alpha-release.apk) is a dev APK build. Based on the development branch. It should fix the issue

**Comment by muhammadarif1** [comment]
let me try

**Comment by Doomsdayrs** [comment]
How did it go?

**Comment by muhammadarif1** [comment]
the bug still appear on my device!

**Comment by muhammadarif1** [comment]
https://youtu.be/aZRGAY3xhdI

```FATAL EXCEPTION: AsyncTask #5
Process: com.github.doomsdayrs.apps.shosetsu, PID: 12535
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NoSuchMethodError: No static method encodeBase64String([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/ext.jar)
	at com.github.doomsdayrs.apps.shosetsu.backend.database.Database.serialize(Database.java:126)
	at com.github.doomsdayrs.apps.shosetsu.backend.database.Database.access$000(Database.java:54)
	at com.github.doomsdayrs.apps.shosetsu.backend.database.Database$DatabaseLibrary.addToLibrary(Database.java:545)
	at com.github.doomsdayrs.apps.shosetsu.backend.async.NovelLoader.doInBackground(NovelLoader.java:92)
	at com.github.doomsdayrs.apps.shosetsu.backend.async.NovelLoader.doInBackground(NovelLoader.java:41)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more```

**Comment by Doomsdayrs** [comment]
Did you uninstall the application first?

**Comment by muhammadarif1** [comment]
of course'

**Comment by Doomsdayrs** [comment]
Completely uninstall, and try this [version](https://cdn.discordapp.com/attachments/440248692562198528/603631818335453337/shosetsu-v1.1.8.2-alpha-release.apk).

**Comment by muhammadarif1** [comment]
let me try

**Comment by muhammadarif1** [comment]
it works as well now
