### ISSUE TITLE
crash when try to open the app

### ISSUE THREAD

**Issue by muhammadarif1** [Doomsdayrs/shosetsu#3]
android 5.1
device oppo neo 5
```FATAL EXCEPTION: main
Process: com.github.doomsdayrs.apps.shosetsu, PID: 3505
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.doomsdayrs.apps.shosetsu/com.github.doomsdayrs.apps.shosetsu.MainActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2525)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2617)
	at android.app.ActivityThread.access$800(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
	at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:555)
	at android.app.Activity.onApplyThemeResource(Activity.java:3764)
	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
	at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:90)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2465)
	... 10 more```

**Comment by muhammadarif1** [comment]
@Doomsdayrs

**Comment by Doomsdayrs** [comment]
This seems to be an issue built into XML. Maybe the new version will fix this issue, otherwise i need to really dig into things to figure it out

**Comment by Doomsdayrs** [comment]
Have you attempted the latest versions of the app?

**Comment by muhammadarif1** [comment]
It work nows, i can open the apl as well, but i found another crash, i will subtmite new issue asap

**Comment by Doomsdayrs** [comment]
Great!
