### ISSUE TITLE
[Bug] Crash on chapter open (With global search)

### ISSUE THREAD

**Issue by Doomsdayrs** [Doomsdayrs/shosetsu#57]
**Describe the bug**
After using global search, opening a resulting novel and selecting a chapter crashes app

**To Reproduce**
1. Go to catalogue
2. Global search `dunge`
3. Select Dungeon Hunter and wait for load
4. Select chapter 17-20
5. Crash

**Expected behavior**
Opening up chapter to read

**Screenshots**
https://mega.nz/#!MBBhXARa!2E50WexeWuX6BF8F5GHdffUE0UUTYwU2CWNEISwPGrc

**Device information:**
 - OS: LDPlayer 3.76
 - App Version: v1.0.0

**Comment by Doomsdayrs** [comment]
(Issue from 304648989935140876)

**Comment by Doomsdayrs** [comment]
Error
```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.doomsdayrs.apps.shosetsu, PID: 6002
    java.lang.RuntimeException: Parcel: unable to marshal value com.github.doomsdayrs.apps.shosetsu.ui.search.SearchFragment$StoredData@33b83c8
        at android.os.Parcel.writeValue(Parcel.java:1782)
        at android.os.Parcel.writeList(Parcel.java:1045)
        at android.os.Parcel.writeValue(Parcel.java:1729)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.os.Parcel.writeBundle(Parcel.java:997)
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:169)
        at android.os.Parcel.writeTypedObject(Parcel.java:1634)
        at android.os.Parcel.writeTypedList(Parcel.java:1513)
        at android.os.Parcel.writeTypedList(Parcel.java:1470)
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51)
        at android.os.Parcel.writeParcelable(Parcel.java:1801)
        at android.os.Parcel.writeValue(Parcel.java:1707)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4505)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)```

**Comment by Doomsdayrs** [comment]
Mistake close

**Comment by Doomsdayrs** [comment]
01e98ac
Issue with serializing, Fixed
